node {
    stage('Code checkout') {
        checkout scm
    }

    stage('Build image') {
        sh "sudo -S docker-compose -f ./user_management/docker-compose.yml build"
    }
	
    stage('Push image') {
	withCredentials([usernamePassword( credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
	    def registry_url = "registry.hub.docker.com/"
            sh "sudo -S docker login -u $USER -p $PASSWORD ${registry_url}"
            docker.withRegistry("http://${registry_url}", "docker-hub-credentials") {
	        sh "sudo -S docker push thertion12/user-management"
		sh "sudo -S docker tag postgres:10 thertion12/postgres"
		sh "sudo -S docker push thertion12/postgres"
		    
		    
	    }
	}
    }
}
