node {
    stage('Code checkout') {
        checkout scm
    }

    stage('Build image') {
	    	bat "cd"
	    	bat "dir"
		bat "docker-compose -f user-management\\docker-compose.yml build"
    }
	
	stage('Test image') {
		bat "docker-compose up"
	}

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            bat "docker push thertion12/user_management"
        }
    }
}
