node {
    stage('Code checkout') {
        checkout scm
    }

    stage('Build image') {
        sh "sudo -S docker network create --driver bridge blitzkrieg-default-network || true"
        sh "sudo -S docker-compose -f ./kafka-docker/docker-compose.yml build"
        sh "sudo -S docker-compose -f ./kafka-docker/docker-compose.yml up -d"
        sh "sudo -S docker commit zookeeper"
        sh "sudo -S docker commit kafka"
	      sh "sudo -S docker tag `docker images --format='{{.Repository}} {{.ID}}' | grep 'kafka' | head -1 | cut -d' ' -f2` `echo thertion12/kafka`"
   	    sh "sudo -S docker tag `docker images --format='{{.Repository}} {{.ID}}' | grep 'zookeeper' | head -1 | cut -d' ' -f2` `echo thertion12/zookeeper`"
        sh "sudo -S docker-compose -f ./kafka-docker/docker-compose.yml down"
    }
	
    stage('Push image') {
	    withCredentials([usernamePassword( credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
	        def registry_url = "registry.hub.docker.com/"
            sh "sudo -S docker login -u $USER -p $PASSWORD ${registry_url}"
            docker.withRegistry("http://${registry_url}", "docker-hub-credentials") {
	        sh "sudo -S docker push thertion12/kafka"
		      sh "sudo -S docker push thertion12/zookeeper"	    
	      }
	    }
    }
}
