version: "2"
networks:
  default:
    external:
      name: blitzkrieg-default-network
services:
  modelexec:
    container_name: model-executer
    restart: always
    build:
      context: ./model_executor
      dockerfile: Dockerfile
    image: thertion12/model-executer
    ports:
      - "9003:9003"

