version: "2"
networks:
  default:
    external:
      name: blitzkrieg-default-network
services:
  dataret:
    container_name: data-retrieval
    restart: always
    build:
      context: ./data_retrieval
      dockerfile: Dockerfile
    image: thertion12/data-retrieval
    ports:
      - "9002:9002"


  datapost:
    container_name: data-post-process
    restart: always
    build:
      context: ./data_post_analysis
      dockerfile: Dockerfile
    image: thertion12/data-post-process
    ports:
      - "9001:9001"
  modelexec:
    container_name: model-executer
    restart: always
    build:
      context: ./model_executor
      dockerfile: Dockerfile
    image: thertion12/model-executer
    ports:
      - "9003:9003"


