node {
    stage('Code checkout') {
        checkout scm
    }

    stage('Build image') {
    	withCredentials([usernamePassword( credentialsId: 'jenkins-creds', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
	    sh "sudo -S docker-compose -f ./UI/docker-compose.yml build"
	}
    }
	
    stage('Push image') {
	withCredentials([usernamePassword( credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
	    def registry_url = "registry.hub.docker.com/"
            sh "sudo -S docker login -u $USER -p $PASSWORD docker.io"
	    docker.withRegistry("http://${registry_url}", "docker-hub-credentials") {
	        sh "sudo -S docker push thertion12/user-interface"
	    }
	}
    }
    stage('Deploy image') {
	    def registry_url = "registry.hub.docker.com/"
            sh "cd /home/ubuntu/"
	    sh "export KUBECONFIG=/home/ubuntu/config"
	    sh "kubectl apply -f /home/ubuntu/deployment.yml --validate=false"
	
    }
}
